---
# Defines the configuration version.
# The only possible value is "2".
version: "2"

linters:
  # Default set of linters.
  # Allowed values: standard | all | none | fast
  # Default: standard
  default: all

  # Enable specific linters.
  enable: []

  # Disable specific linters.
  disable:
    - depguard
    - mnd       # Overlaps with revive(add-constant)
    - wsl       # Deprecated since v2.2.0

  # All available settings of specific linters.
  settings:
    exhaustruct:
      exclude:
        - '.*/http\.Server'
    gocritic:
      enable-all: true
      disabled-tags:
        - experimental
    govet:
      enable-all: true
      disable: []
      settings:
        shadow:
          strict: true
    revive:
      enable-all-rules: true
      rules:
        - name: add-constant
          disabled: false
          arguments:
            - allow-ints: "0"
        - name: package-comments
          disabled: true
        - name: line-length-limit
          severity: warning
          disabled: true
          arguments: [200]

  # Defines a set of rules to ignore issues.
  # It does not skip the analysis, and so does not ignore "typecheck" errors.
  exclusions:

formatters:
  # Enable specific formatters.
  # Default: [] (uses standard Go formatting) 
  enable:
    # Stricter and more consistent formatter than gofmt.
    - gofumpt
    # Manages and sorts import sections (std, external, local).
    - gci
    # Wraps long lines for better readability.
    - golines 

  settings:
    gofumpt:
      # Module path which contains the source code being formatted.
      # Default: ""
      # module-path: github.com/org/project
      module-path: ""
      # Choose whether to use the extra rules.
      # Default: false
      extra-rules: false
    gci:
      # Section configuration to compare against.
      # Section names are case-insensitive and may contain parameters in ().
      # The default order of sections is `standard > default > custom > blank > dot > alias > localmodule`.
      # If `custom-order` is `true`, it follows the order of `sections` option.
      sections:
        # Standard section: captures all standard packages.
        - standard
        # Default section: contains all imports that could not be matched to another section type.
        - default
        # Custom section: groups all imports with the specified Prefix.
        #- prefix(github.com/org/project)
      # Checks that no inline comments are present.
      # Default: false
      no-inline-comments: false
      # Checks that no prefix comments (comment lines above an import) are present.
      # Default: false
      no-prefix-comments: false
      # Enable custom order of sections.
      # If `true`, make the section order the same as the order of `sections`.
      # Default: false
      custom-order: true
      # Drops lexical ordering for custom sections.
      # Default: false
      no-lex-order: false
    golines:
      # Target maximum line length.
      # Default: 100
      max-len: 200
      # Length of a tabulation.
      # Default: 4
      tab-len: 8
      # Shorten single-line comments.
      # Default: false
      shorten-comments: false
      # Struct tag reformatting.
      # Default: true
      reformat-tags: true
      # Split chained methods on the dots as opposed to the arguments.
      # Default: true
      chain-split-dots: true

issues:
  # Maximum issues count per one linter.
  # Set to 0 to disable.
  # Default: 50
  max-issues-per-linter: 0

  # Maximum count of issues with the same text.
  # Set to 0 to disable.
  # Default: 3
  max-same-issues: 0

  # Make issues output unique by line.
  # Default: true
  uniq-by-line: false

  # Show only new issues: if there are unstaged changes or untracked files,
  # only those changes are analyzed, else only changes in HEAD~ are analyzed.
  # It's a super-useful option for integration of golangci-lint into existing large codebase.
  # It's not practical to fix all existing issues at the moment of integration:
  # much better don't allow issues in new code.
  #
  # Default: false
  new: false

  # Show only new issues created after the best common ancestor (merge-base against HEAD).
  # Default: ""
  #new-from-merge-base: "main"

  # Show only new issues created after git revision `REV`.
  # Default: ""
  #new-from-rev: HEAD

  # Show only new issues created in git patch with set file path.
  # Default: ""
  #new-from-patch: path/to/patch/file

  # Show issues in any part of update files (requires new-from-rev or new-from-patch).
  # Default: false
  #whole-files: true

  # Apply the fixes detected by the linters and formatters (if it's supported by the linter).
  # Default: false
  fix: false

output:
  sort_order:
    - linter
    - severity
    - file # filepath, line, and column.

run:
  # Timeout for total work, e.g. 30s, 5m, 5m30s.
  # Default: 0 (disabled)
  timeout: 5m

  # The mode used to evaluate relative paths.
  # It's used by exclusions, Go plugins, and some linters.
  # - `gomod`: the paths will be relative to the directory of the `go.mod` file.
  relative-path-mode: gomod

  # Exit code when at least one issue was found.
  # Default: 1
  issues-exit-code: 1

  # Include test files or not.
  # Default: true
  tests: true

  # Allow multiple parallel golangci-lint instances running.
  # If false, golangci-lint acquires file lock on start.
  # Default: false
  allow-parallel-runners: true

severity:
